#! /usr/bin/env bash

OUTFILE=${1:-/dev/stdout}

nix-env -qa -P | awk '{print $1}' | grep 'nixos\.' > $OUTFILE
nix-env -f '<nixpkgs>' -qaP -A haskellPackages | \
    awk '{print "nixos."$1}' >> $OUTFILE
#vim: ft=sh
